### ISSUE TITLE
Feedback Quiz Lv4-blog

### ISSUE THREAD

**Issue by udiiin** [yunusbahtiar22/hsi-sandbox-lv4-2#1]
Halo Mas @yunusbahtiar22, terima kasih utk submissionnya...

Saya ada beberpa minor feedback:

**1.)**  
Naming variable best practice: jika array gunakan _plural_ (jamak), jika single item gunakan _singular_, termasuk ketika looping.  
👉 `products.map((product) => ... )`  
👉 `pages.flatMap((page) => ... )` 💡 

**2.)**  
Button "Load More":
```jsx
{hasNextPage && (
  <Button
    ...
    disabled={!hasNextPage}>
    {isFetchingNextPage ? <Loader size="md" /> : "Load More"}
  </Button>
)}
```
Lebih tepat seperti ini: `disabled={isFetchingNextPage}`.

**3.)**  
Terkait penggunaan _try-catch_ & _throw_,  
Code seperti ini:
```js
try {
  doSomething();
} catch (err) {
  throw err;
}
```
Itu technically sama persis dengan code ini:
```js
doSomething();
```
Jadi kalo di dalam catch itu ujung2nya sekedar _throw error_, maka sebaiknya langsung saja tidak perlu _try-catch_.

**4.)**  
Fungsi `getNextPageParam` bisa dipersimpel gini:
```js
getNextPageParam: ({ meta }) =>
  meta.pagination.page < meta.pagination.totalPages
    ? meta.pagination.page + 1
    : undefined,
```

.

Barokallaahu fiik...

**Comment by yunomeister22** [comment]
terimakasih untuk feedbacknya mas @udiiin, sudah diperbaiki yaa
jazakallahu khoiron

**Comment by afiiif** [comment]
Sipp mas, udah oke ✅

**Comment by udiiin** [comment]
Sipp mas, udah oke ✅
